
name = "rsvp"
main = "src/index.js"
compatibility_date = "2024-06-01"

kv_namespaces = [
  { binding = "REUNION_KV", id = "your_kv_namespace_id_here" }
]

[vars]
DKIM_PRIVATE_KEY = "your_dkim_private_key_here"
